// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCadVJTTR4UmXnrr4qqr0shwaMvnjB4JOU',
    appId: '1:312020372463:web:4a50d48cf62b24dc20841a',
    messagingSenderId: '312020372463',
    projectId: 'fir-flutter-codelab-6a206',
    authDomain: 'fir-flutter-codelab-6a206.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-6a206.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi9fVoeB8WgXsRIchplSK8lUA45898AwM',
    appId: '1:312020372463:android:54513fc9ad1307f420841a',
    messagingSenderId: '312020372463',
    projectId: 'fir-flutter-codelab-6a206',
    storageBucket: 'fir-flutter-codelab-6a206.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1NLT5s-3X46nDA52lsvkcfGjwf9Y7So',
    appId: '1:312020372463:ios:d839f22d22428a7520841a',
    messagingSenderId: '312020372463',
    projectId: 'fir-flutter-codelab-6a206',
    storageBucket: 'fir-flutter-codelab-6a206.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn1NLT5s-3X46nDA52lsvkcfGjwf9Y7So',
    appId: '1:312020372463:ios:d839f22d22428a7520841a',
    messagingSenderId: '312020372463',
    projectId: 'fir-flutter-codelab-6a206',
    storageBucket: 'fir-flutter-codelab-6a206.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCadVJTTR4UmXnrr4qqr0shwaMvnjB4JOU',
    appId: '1:312020372463:web:e62b792329ea35a020841a',
    messagingSenderId: '312020372463',
    projectId: 'fir-flutter-codelab-6a206',
    authDomain: 'fir-flutter-codelab-6a206.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-6a206.appspot.com',
  );
}
